2022-02-14 16:22:01 [INFO] 获得列名:attach====成功 [case.py:14]
2022-02-14 16:22:01 [INFO] 获取入口成功，服务器：debug；数据库：debug [conf.py:10]
2022-02-14 16:22:01 [INFO] 获取服务器信息成功:http://192.168.222.154:80 [conf.py:20]
2022-02-14 16:22:01 [INFO] 读取excel文件:../excelcases/attach.xlsx====成功 [case.py:34]
2022-02-14 16:22:01 [INFO] 发送请求====成功 [case.py:80]
2022-02-14 16:22:01 [ERROR] 获得响应结果中的对应参数值====失败，失败类型：TypeError,失败内容：'>' not supported between instances of 'list' and 'int' [case.py:53]
2022-02-14 16:22:01 [ERROR] 存入公共字典====失败，失败类型：SystemExit,失败内容：None [case.py:63]
